### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by RadiologieSLK** [trypear/pearai-master#4]
Hi,

I want to use my own OpenAI API Key, which I successfully entered in PearAI. Now I want to logout or sing out off a PearAI account, which I don't need.

1. How can I logout?
2. How can I delete my PearAI account?

Thank you

**Comment by nang-dev** [comment]
Command Pallete (Cmd+Shift+P)
Logout of PearAI

Account deletion: I can help you, whats ur email
